### ISSUE TITLE
Problems with adding custom keymaps

### ISSUE THREAD

**Issue by primeapple** [andrewferrier/debugprint.nvim#42]
Hi, first of all thanks for the plugin.

I have some problems with setting custom keymaps, maybe you could have a look?
My setup in Packer currently looks like this.

```lua
    use {
        'andrewferrier/debugprint.nvim',
        config = function()
            require('debugprint').setup({
                create_keymaps = false,
            })
            vim.keymap.set('n', 'g??', function() require('debugprint').debugprint({variable = true}) end)
            vim.keymap.set('v', 'g?', function() require('debugprint').debugprint({variable = true}) end)
            vim.keymap.set('o', 'g?', function() require('debugprint').debugprint({variable = true}) end)
        end,
    }
```

The normal mode mapping does nothing when the cursor is on a variable name.
The visual mode mapping does nothing as well.
The operator mode mapping converts the variable to rot-13.

**Comment by andrewferrier** [comment]
@primeapple thanks for your feedback!

It sounds to me like maybe the plugin isn't being loaded at all, or your config function isn't being run.

What do you see when you run `:nmap g?` ? This should tell you what the mapping is configured to do.

Try running the command `:DeleteDebugPrints`. That should be created when you/load require `debugprint`. If it isn't, then probably it's not being loaded correctly.

**Comment by andrewferrier** [comment]
Also, another simpler test you can do test: can you try removing your custom keymaps (and the `create_keymaps` attribute) and simply try one of the inbuilt keymaps? e.g. `g?v`. Let's see if that works...

**Comment by primeapple** [comment]
The command `:DeleteDebugPrints` is there, so the plugin gets loaded.

The default inbuilt commands work.

**Comment by andrewferrier** [comment]
@primeapple aha, OK, I think I see the problem now!

Because of the way the keymappings work for `debugprint` (this is required to make the dot-repeat work), it's essential have a 'return' inside the callback function for your keymapping, as well as make it an `expr` mapping. This was not correctly shown in the README, sorry. I've now fixed that: https://github.com/andrewferrier/debugprint.nvim#keymappings-and-commands.

Please check and tweak the way your keymappings are set up. I think it should be more like:

```lua
vim.keymap.set('n', 'g??', function() return require('debugprint').debugprint({variable = true}) end, { expr = true })
vim.keymap.set('v', 'g?', function() return require('debugprint').debugprint({variable = true}) end, { expr = true })
vim.keymap.set('o', 'g?', function() return require('debugprint').debugprint({variable = true}) end, { expr = true })
```

Please let me know if that fixes your issue.

Also, I was thinking about changing the way the keymappings are customized to instead make it more 'automatic' for the user by allowing them to just pass in the required keys themselves into the `setup()` function, and setting up the key mappings for them. This is something many other NeoVim plugins do. Do you think that would be useful, or do you prefer this approach?

**Comment by primeapple** [comment]
The setting of the keymaps works now, at least with the visual and normal mode.

The operator pending mode is still not working, tho...
I'll investigate further in the following days.

**Comment by andrewferrier** [comment]
@primeapple thanks, well spotted. I've fixed that now in the docs.

I'll close this for now. Thanks for your patience and thanks for your help in finding these issues.
